//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dad_2018_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Client = new HashSet<Client>();
            this.Owner = new HashSet<Owner>();
        }
    
        public int Id { get; set; }
        public string CityName { get; set; }
    
        public virtual ICollection<Client> Client { get; set; }
        public virtual ICollection<Owner> Owner { get; set; }
    }
}
