//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dad_2018_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.PropertySales = new HashSet<PropertySales>();
            this.SalesDetail = new HashSet<SalesDetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Contact_No { get; set; }
        public string E_Mail { get; set; }
    
        public virtual ICollection<PropertySales> PropertySales { get; set; }
        public virtual ICollection<SalesDetail> SalesDetail { get; set; }
    }
}
